{% extends "bayesn.yaml" %}
{% block guide %}
  - cls: HierarchicPartialMultivariateNormalSamplingGroup
    name: hpmvn
    match: [ Om0, Ode0, Rv, tau, delta_M, Av, theta ]
    diag: [ Av, theta, delta_M$ ]
    init_scale_full: 0.01
    init_scale_diag: 0.01
    init_scale_const_corr: 0.01
    hdims: {Av: 0, theta: 1, delta_M: 0}
{% endblock %}