{% extends "bayesn.yaml" %}
{% block guide %}
  - cls: MVN
    name: mvn
    match: [Om0, Ode0, Rv, tau, delta_M/scale]
    init_scale: 0.01
  - cls: DiagonalNormalSamplingGroup
    name: diag
    match: [ Av, theta, delta_M$ ]
    init_scale: 0.01
{% endblock %}