from snai.tossn.sources.abc import ColouredSource, DelayedGridInterpPCASource
from ..utils import _t


class SNEMOSource(ColouredSource, DelayedGridInterpPCASource):
    A_s: _t

    def colourlaw(self, phase: _t, wave: _t) -> _t: ...

    def __call__(self, phase: _t, wave: _t, *, c_0: _t = 1., coeffs: _t = 0., A_s: _t = 0., **kwargs): ...

class SNEMO2Source(SNEMOSource): ...
class SNEMO7Source(SNEMOSource): ...
class SNEMO15Source(SNEMOSource): ...
